import random 
print(random.randint(1, 10))
import random as rn 
print(rn.randint(1, 10))
random.randrange(1, 10)
import random
random.randrange(1, 10)
from math import pi 
print(pi)   

import custom
from math import sin
sin(1)

from math import * 
sqrt(2)    
ceil(2.7)

def sqrt(num):    print("I don't know what's the square root of {}.".format(num)) sqrt(4)
#round
x = 1.55 y = -1.55
round(x)       
round(y)
round(x, 1)    
round(y, 1)
import math
math.floor(x)  
math.floor(y) 
math.ceil(x)   
math.ceil(y)
math.trunc(x)
math.trunc(y)
math.hypot(2, 4)
math.radians(45) 
math.degrees(math.asin(1))
math.sin(math.pi / 2)
math.sin(math.radians(90))
math.asin(1)
math.asin(1) / math.pi
math.cos(math.pi / 2)
math.acos(1)
math.tan(math.pi/2)
math.atan(math.inf)
math.atan(float('inf'))
math.atan2(1, 2) 
math.atan2(-1, -2)
math.atan2(1, 0) 
math.sinh(math.pi)
math.asinh(1) 
math.cosh(math.pi)
math.acosh(1)
math.tanh(math.pi)
math.atanh(0.5)
math.log(math.e)
math.log(1) 
math.log(100)
math.log(1 + 1e-20)
math.log1p(1e-20) 
math.log10(10)
math.log(100, 10)
math.log(27, 3)
math.log(1, 10)
math.copysign(-2, 3)    
math.copysign(3, -3)
math.copysign(4, 14.2) 
math.copysign(1, -0.0) 
abs(1 + 1j)
complex(1)
complex(imag=1)
complex(1, 1)
complex('1+1j')
complex('1 + 1j')
round(1.3) 
round(0.5)  
round(1.5)
round(1.3)  
round(1.33, 1) 
round(0.5)  
round(1.5) 
round(2.675, 2)
math.floor(-1.7)

import cmath 
cmath.sqrt(-1)
math.sqrt(-1)
cmath.polar(1 + 1j)
abs(1 + 1j), cmath.phase(1 + 1j)
cmath.rect(math.sqrt(2), math.atan(1))
cmath.phase(complex(-1.0, 0.0))
cmath.phase(complex(-1.0, -0.0))
cmath.log(1+1j)
cmath.exp(1j * cmath.pi)
type(cmath.pi)
cmath.isinf(complex(float('inf'), 0.0))
cmath.isnan(0.0, float('nan'))
cmath.isinf(complex(0.0, math.inf))
cmath.isnan(complex(math.nan, 0.0))
z = cmath.rect(*cmath.polar(1+1j)
cmath.isclose(z, 1+1j)

import cmath
z = 2+3j
cmath.phase(z)
cmath.polar(z)
cmath.rect(2, cmath.pi/2)
cmath.exp(z)
cmath.log(z)
cmath.log10(-100)
cmath.sqrt(z)
cmath.sin(z) 
cmath.cos(z)
cmath.tan(z)
cmath.asin(z)
cmath.acos(z)
cmath.atan(z) 
cmath.sin(z)**2 + cmath.cos(z)**2 
cmath.sinh(z)
cmath.cosh(z)
cmath.tanh(z) 
cmath.asinh(z)
cmath.acosh(z)
cmath.atanh(z)
cmath.cosh(z)**2 - cmath.sin(z)**2 
cmath.cosh((0+1j)*z) - cmath.cos(z)

z = 2+3j
abs(z) 
z.conjugate()
arr = ['a', 'b', 'c', 'd']
print(arr[0])
print(arr[1])
print(arr[-2])
